// Client-side loader for posts and research that live in a separate GitHub repo.
// The repo contains index.json (generated by its GitHub Action), posts/*.md and research/*.
import { marked } from "marked";
import DOMPurify from "dompurify";
import { contentBaseUrl, contentViewUrl, url } from "../data/site";

export interface PostEntry {
  slug: string;
  file: string;
  title: string;
  date: string;
  tags: string[];
  summary?: string;
  cover?: string;
}

const SLUG = /^[a-z0-9][a-z0-9._-]*$/i;

export function isValidSlug(slug: string | null): slug is string {
  return !!slug && SLUG.test(slug);
}

export function postHref(slug: string): string {
  return `${url("/posts/view/")}?p=${encodeURIComponent(slug)}`;
}

function base(): string {
  const b = contentBaseUrl();
  return b.endsWith("/") ? b : `${b}/`;
}

/** Resolve a path from the content repo (relative to the repo root, or to a post file). */
export function repoUrl(path: string, relativeTo = ""): string {
  return new URL(path, new URL(relativeTo, new URL(base(), location.href))).href;
}

export interface ResearchEntry {
  slug: string;
  file: string;
  title: string;
  summary: string;
  status: string;
  tags: string[];
  date?: string;
  venue?: string;
  /** Where the paper lives (e.g. ResearchGate); the row opens it in a new window. */
  url?: string;
  /** Repo path of the PDF, e.g. "research/minicollide.pdf". */
  pdf?: string;
  code?: string;
}

interface ContentIndex {
  posts: PostEntry[];
  research: ResearchEntry[];
}

// One fetch per page, shared by every list that needs the index.
let indexPromise: Promise<ContentIndex> | undefined;

export function loadContentIndex(): Promise<ContentIndex> {
  indexPromise ??= (async () => {
    const res = await fetch(repoUrl("index.json"), { cache: "no-cache" });
    if (!res.ok) throw new Error(`Could not load content (HTTP ${res.status})`);
    const data = (await res.json()) as Partial<ContentIndex> | PostEntry[];
    const posts = Array.isArray(data) ? data : (data.posts ?? []);
    const research = Array.isArray(data) ? [] : (data.research ?? []);
    const byDate = (a: { date?: string }, b: { date?: string }) => ((a.date ?? "") < (b.date ?? "") ? 1 : -1);
    return {
      posts: posts.filter((p) => isValidSlug(p.slug)).sort(byDate),
      research: research.filter((r) => isValidSlug(r.slug)).sort(byDate),
    };
  })();
  // Let a later call retry after a failure.
  indexPromise.catch(() => (indexPromise = undefined));
  return indexPromise;
}

export async function loadIndex(): Promise<PostEntry[]> {
  return (await loadContentIndex()).posts;
}

export async function loadResearch(): Promise<ResearchEntry[]> {
  return (await loadContentIndex()).research;
}

/** Minimal frontmatter parser: `key: value` and `key: [a, b]` lines. */
export function parseFrontmatter(md: string): { data: Record<string, string | string[]>; body: string } {
  const m = md.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?/);
  if (!m) return { data: {}, body: md };
  const data: Record<string, string | string[]> = {};
  for (const line of m[1].split(/\r?\n/)) {
    const kv = line.match(/^([A-Za-z0-9_-]+):\s*(.*)$/);
    if (!kv) continue;
    const raw = kv[2].trim();
    const unquote = (s: string) => s.trim().replace(/^["']|["']$/g, "");
    data[kv[1]] = raw.startsWith("[") && raw.endsWith("]")
      ? raw.slice(1, -1).split(",").map(unquote).filter(Boolean)
      : unquote(raw);
  }
  return { data, body: md.slice(m[0].length) };
}

export async function loadPost(slug: string, index?: PostEntry[]) {
  const entry = index?.find((p) => p.slug === slug);
  const file = entry?.file ?? `posts/${slug}.md`;
  const res = await fetch(repoUrl(file), { cache: "no-cache" });
  if (res.status === 404) return null;
  if (!res.ok) throw new Error(`Could not load post (HTTP ${res.status})`);
  const { data, body } = parseFrontmatter(await res.text());
  const tags = Array.isArray(data.tags) ? data.tags : entry?.tags ?? [];
  return {
    slug,
    file,
    title: String(data.title ?? entry?.title ?? slug),
    date: String(data.date ?? entry?.date ?? ""),
    tags,
    summary: String(data.summary ?? entry?.summary ?? ""),
    html: renderMarkdown(body, file),
  };
}

/** Markdown -> sanitized HTML, with relative links/images pointed at the posts repo. */
export function renderMarkdown(md: string, file: string): string {
  const html = DOMPurify.sanitize(marked.parse(md, { async: false, gfm: true }));
  const tpl = document.createElement("template");
  tpl.innerHTML = html;
  const isRelative = (v: string) => !/^([a-z][a-z0-9+.-]*:|\/\/|#)/i.test(v);
  tpl.content.querySelectorAll<HTMLImageElement>("img[src]").forEach((img) => {
    const src = img.getAttribute("src")!;
    if (isRelative(src)) img.src = repoUrl(src, file);
    img.loading = "lazy";
  });
  tpl.content.querySelectorAll<HTMLAnchorElement>("a[href]").forEach((a) => {
    const href = a.getAttribute("href")!;
    const post = href.match(/^(?:\.\/)?([^/]+)\.md$/);
    if (post && isValidSlug(post[1])) a.href = postHref(post[1]);
    else if (isRelative(href)) a.href = repoUrl(href, file);
    if (/^https?:/i.test(a.href) && new URL(a.href).origin !== location.origin) {
      a.target = "_blank";
      a.rel = "noopener noreferrer";
    }
  });
  return tpl.innerHTML;
}

export function escapeHtml(s: string): string {
  return s.replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]!);
}

export function formatDate(iso: string): string {
  const d = new Date(`${iso.slice(0, 10)}T00:00:00`);
  return isNaN(d.getTime()) ? iso : d.toLocaleDateString("en", { year: "numeric", month: "short", day: "numeric" });
}

const ARROW = `<svg width="16" height="16" viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><path d="M4 12 12 4M5.5 4H12v6.5"/></svg>`;

// Tile artwork cycles like the reference's featured-work grid: ink, signal red, mist.
const TILE = ["bg-ink text-paper", "bg-signal text-paper", "bg-mist text-ink"];

/** Home page tile: artwork block with the caption underneath. */
export function postCardHtml(p: PostEntry, i = 0): string {
  const art = p.cover
    ? `<img src="${escapeHtml(repoUrl(p.cover))}" alt="" loading="lazy" class="absolute inset-0 h-full w-full bg-white object-contain p-3 transition duration-500 group-hover:scale-[1.03]" />`
    : `<span class="absolute inset-0 flex items-center p-6 font-display text-4xl uppercase leading-[0.95]">${escapeHtml(p.title)}</span>`;
  return `
    <li>
      <a href="${postHref(p.slug)}" class="group block">
        <div class="relative aspect-[4/3] overflow-hidden ${TILE[i % TILE.length]}">${art}</div>
        <p class="mt-4 text-[13px] font-extrabold uppercase leading-snug tracking-tight transition group-hover:text-signal">${escapeHtml(p.title)}</p>
        <p class="mt-1 text-xs text-ink/60">${escapeHtml(formatDate(p.date))}${p.tags.length ? ` · ${escapeHtml(p.tags.join(", "))}` : ""}</p>
      </a>
    </li>`;
}

/** Posts page row. */
export function postRowHtml(p: PostEntry, i = 0): string {
  const n = String(i + 1).padStart(2, "0");
  const tags = p.tags
    .map((t) => `<span class="border border-ink/25 px-2 py-0.5 text-[11px] font-semibold uppercase tracking-wider">${escapeHtml(t)}</span>`)
    .join("");
  return `
    <li class="border-b border-ink/15">
      <a href="${postHref(p.slug)}" class="group grid gap-4 py-8 transition hover:bg-mist sm:grid-cols-[64px_1fr_auto] sm:gap-8 sm:px-4 lg:grid-cols-[64px_1fr_280px_auto]">
        <span class="font-display text-3xl text-signal">${n}</span>
        <span class="flex flex-col gap-3">
          <span class="text-xl font-extrabold uppercase leading-[1.1] tracking-tight transition group-hover:text-signal sm:text-2xl">${escapeHtml(p.title)}</span>
          ${p.summary ? `<span class="max-w-2xl text-sm leading-relaxed text-ink/70">${escapeHtml(p.summary)}</span>` : ""}
        </span>
        <span class="flex flex-col gap-3 sm:col-start-2 lg:col-start-auto">
          <span class="text-[11px] font-bold uppercase tracking-[0.12em] text-ink/60">${escapeHtml(formatDate(p.date))}</span>
          <span class="flex flex-wrap gap-2">${tags}</span>
        </span>
        <span class="hidden self-center transition group-hover:translate-x-0.5 group-hover:-translate-y-0.5 group-hover:text-signal sm:block">${ARROW}</span>
      </a>
    </li>`;
}

/** Home grid filler shown until there are enough posts. */
export function placeholderHtml(i: number): string {
  return `
    <li aria-hidden="true" class="hidden md:block">
      <div class="relative flex aspect-[4/3] items-end p-6 ${TILE[i % TILE.length]}">
        <span class="font-display text-3xl uppercase leading-none opacity-40">Next post<br />in progress</span>
      </div>
      <p class="mt-4 text-[13px] font-extrabold uppercase tracking-tight text-ink/40">Coming soon</p>
    </li>`;
}

const STATUS_STYLE: Record<string, string> = {
  published: "bg-signal text-paper",
  ongoing: "bg-ink text-paper",
  idea: "border border-ink",
};

const ext = (href: string) => `href="${escapeHtml(href)}" target="_blank" rel="noopener noreferrer"`;

/** Research row: the whole row opens the paper in a new window; PDF/Code links sit on top. */
export function researchRowHtml(r: ResearchEntry, i = 0): string {
  const n = String(i + 1).padStart(2, "0");
  const main = r.url ?? (r.pdf ? contentViewUrl(r.pdf) : undefined);
  const title = main
    ? `<a ${ext(main)} class="after:absolute after:inset-0 group-hover:text-signal">${escapeHtml(r.title)}</a>`
    : escapeHtml(r.title);
  const meta = [r.venue, r.date ? formatDate(r.date) : ""].filter(Boolean)
    .map((m) => `<span class="text-ink/60">${escapeHtml(m!)}</span>`).join("");
  const tags = r.tags
    .map((t) => `<span class="border border-ink/25 px-2 py-0.5 text-[11px] font-semibold uppercase tracking-wider">${escapeHtml(t)}</span>`)
    .join("");
  const link = (label: string, href: string) =>
    `<a ${ext(href)} class="inline-flex items-center gap-2 border-b-2 border-signal pb-0.5 text-[11px] font-bold uppercase tracking-[0.12em] hover:text-signal">${label} ${ARROW}</a>`;
  const links = [r.pdf ? link("PDF", contentViewUrl(r.pdf)) : "", r.code ? link("Code", r.code) : ""].join("");
  return `
    <li class="group relative border-b border-ink/15">
      <div class="grid gap-4 py-8 transition group-hover:bg-mist sm:grid-cols-[64px_1fr_auto] sm:gap-8 sm:px-4 lg:grid-cols-[64px_1fr_280px_auto]">
        <span class="font-display text-3xl text-signal">${n}</span>
        <div class="flex flex-col gap-3">
          <h3 class="text-xl font-extrabold uppercase leading-[1.1] tracking-tight sm:text-2xl">${title}</h3>
          ${r.summary ? `<p class="max-w-2xl text-sm leading-relaxed text-ink/70">${escapeHtml(r.summary)}</p>` : ""}
        </div>
        <div class="flex flex-col gap-3 sm:col-start-2 lg:col-start-auto">
          <div class="flex flex-wrap items-center gap-3 text-[11px] font-bold uppercase tracking-[0.12em]">
            <span class="px-2.5 py-1 ${STATUS_STYLE[r.status] ?? STATUS_STYLE.idea}">${escapeHtml(r.status)}</span>${meta}
          </div>
          <div class="flex flex-wrap gap-2">${tags}</div>
          ${links ? `<div class="relative z-10 flex flex-wrap gap-4">${links}</div>` : ""}
        </div>
        <span class="hidden self-center transition group-hover:-translate-y-0.5 group-hover:translate-x-0.5 group-hover:text-signal sm:block" aria-hidden="true">${ARROW}</span>
      </div>
    </li>`;
}
